//ban
recipes.remove(<industrialforegoing:range_addon:11>);
recipes.remove(<industrialforegoing:range_addon:10>);
recipes.remove(<industrialforegoing:range_addon:9>);
recipes.remove(<industrialforegoing:range_addon:8>);
recipes.remove(<industrialforegoing:range_addon:7>);
recipes.remove(<industrialforegoing:range_addon:6>);
recipes.remove(<industrialforegoing:range_addon:5>);
recipes.remove(<industrialforegoing:enchantment_extractor>);
recipes.remove(<industrialforegoing:enchantment_invoker>);